[package]
name = "sketches"
version = "0.1.0"
edition = "2021"
description = "Wasm bindings for Datadog's DDSketch"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libdd-ddsketch = { git = "https://github.com/DataDog/libdatadog.git", rev = "1b9b7a26f54f116a0f6525abdcd2013b341921a7" }
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]
