[package]
name = "libdatadog-data-pipeline"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
thiserror = "1"

[dependencies.libdd-capabilities]
git = "https://github.com/DataDog/libdatadog.git"
rev = "7327f3049c281090f7cce7830b9430206fba11cf"
default-features = false

[dependencies.libdd-data-pipeline-core]
git = "https://github.com/DataDog/libdatadog.git"
rev = "9fb27ea309363bb4852d093a8e5c85b1c0b9a7d0"
default-features = false

[dependencies.libdd-trace-utils]
git = "https://github.com/DataDog/libdatadog.git"
rev = "7327f3049c281090f7cce7830b9430206fba11cf"
default-features = false

[features]
default = []
compression = ["libdd-data-pipeline-core/compression"]
regex-lite = ["libdd-data-pipeline-core/regex-lite"]
