[package]
name = "libdatadog-data-pipeline"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
thiserror = "1"

[dependencies.libdd-capabilities]
git = "https://github.com/DataDog/libdatadog.git"
rev = "3fa1d1395022d3f3fcff6215cc8aa22d5df616df"
default-features = false

[dependencies.libdd-data-pipeline-core]
git = "https://github.com/DataDog/libdatadog.git"
rev = "3fa1d1395022d3f3fcff6215cc8aa22d5df616df"
default-features = false

[dependencies.libdd-trace-utils]
git = "https://github.com/DataDog/libdatadog.git"
rev = "3fa1d1395022d3f3fcff6215cc8aa22d5df616df"
default-features = false

[features]
default = []
compression = ["libdd-data-pipeline-core/compression"]
regex-lite = ["libdd-data-pipeline-core/regex-lite"]
