[package]
name = "libdatadog"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "libdatadog"

[dependencies]
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"
libdd-ddsketch = "1.1.1"
zstd = { version = "0.13.3", default-features = false, features = ["thin"] }

[build-dependencies]
napi-build = "2"
