[package]
name = "process-discovery"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
libdd-library-config = { path = "../../../libdatadog/libdd-library-config", features = ["otel-thread-ctx"] }
libdd-trace-protobuf = { path = "../../../libdatadog/libdd-trace-protobuf" }

napi = { version = "2" }
napi-derive = { version = "2", default-features = false }
