[package]
name = "datadog-js-zstd"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
zstd = "0.13.3"
js-sys = "0.3.77"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
