name: Release

on:
  push:
    branches:
      - v0.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      package-manager: 'npm'
      cache: false
      min-node-version: 14
      rust: true
      only: linux-arm64,linux-x64,linuxmusl-arm64,linuxmusl-x64

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: npm
    permissions:
      contents: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      pkgjson: ${{ steps.pkg.outputs.json }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
      - id: pkg
        run: |
          content=`cat ./package.json | tr '\n' ' '`
          echo "::set-output name=json::$content"
      - run: |
          git tag v${{ fromJson(steps.pkg.outputs.json).version }}
          git push origin v${{ fromJson(steps.pkg.outputs.json).version }}
